### ISSUE TITLE
Support "cross"

### ISSUE THREAD

**Issue by wdv4758h** [PyO3/setuptools-rust#10]
[cross](https://github.com/japaric/cross) is a great tool for cross compile Rust code to other platform, support it will be awesome ! (so build Python wheel for more platform will be easier)

modification we may need:

* let user can build wheel for different target platform (need to pass `--target $TARGET` to rustc)
* install `cross`, this will be required only if you want to use `cross` feature
* let build command pass `cross` instead of `cargo` (if user choose `cross`)

**Comment by fafhrd91** [comment]
that would be awesome if we could cross compile wheels!

**Comment by AraHaan** [comment]
Actually you can. With the right rust toolsets that is. The wheels are essentially zip files renamed to who and files seem to be set at compression level 0 (store).

**Comment by messense** [comment]
We can have a env var for example `CARGO` defaults to `cargo`, user can override it to `cross`. (much like `$CC`)

**Comment by fafhrd91** [comment]
I wouldn't worry about this for right now

**Comment by mckaymatt** [comment]
Cross helps for platforms that you probably arn't making wheels in.

**Comment by casellimarco** [comment]
Any chance this will be implemented? It would be an awesome and super useful feature!
