### ISSUE TITLE
"ModuleNotFoundError" for setuptools_rust module

### ISSUE THREAD

**Issue by thiyaneshece** [PyO3/setuptools-rust#107]
When i try to install a cryptography library in ubuntu pc, i'm facing an below error. 
Below package is getting installed as part of step in DOCKER IMAGE CREATION.

Collecting cryptography>=2.5 (from paramiko==2.7.2)
18:48:28    Downloading https://files.pythonhosted.org/packages/27/5a/007acee0243186123a55423d49cbb5c15cb02d76dd1b6a27659a894b13a2/cryptography-3.4.4.tar.gz 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-qcmsvhgh/cryptography/setup.py", line 14, in <module>
    from setuptools_rust import RustExtension
   ModuleNotFoundError: No module named 'setuptools_rust'
```
can someone please let me know, how to overcome this issue? 

Setup : 
**OS** - UBUNTU 18. 04. 05 LTS
**Python3 :** 3.6.9

Steps tried out : 
-> I have tried to initiate the same step after upgrade pip install --> however, situation did not improve..
pip - 21.0.1 
semantic-version              2.8.5
setuptools                    40.6.2
setuptools-rust               0.11.6

**Comment by davidhewitt** [comment]
Hi @thiyaneshece thanks for the questions.

Are you using `pip install` to install `cryptography`? 
Is the OS inside your docker image Ubuntu 18.04?

Prebuilt wheels for cryptography should be available for that platform. If you try `pip install wheel` first does this fix your issue?

**Comment by thiyaneshece** [comment]
@davidhewitt : Please find response below.

 -Yes, I'm using pip install to install Paramiko lib which inturn downloads the cryptography library(due to dependency resolve).
- Ubuntu OS is not part of Docker image creation .
- A customized Arch-Linux distribution would be part of Docker image creation.
- Due to this error, docker image creation step is failed.
- This set of py libraries are getting installed properly in windows platform(no docker installation).
- Only when it is getting installed in ubuntu, this issue is being faced.

**Comment by davidhewitt** [comment]
I see. What are the python and pip versions inside the docker image Arch Linux? You may need to add dockerfile steps to update pip and install wheel before attempting to install paramiko.

**Comment by davidhewitt** [comment]
Closing as stale.
