### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/setuptools-rust#132]
I think that `setuptools-rust` works well as-is, so it could be a good time to consider a 1.0 release.

Some things that I propose checking / tweaking before releasing as 1.0:

- [x] `py_limited_api` argument to `RustExtension` should perhaps be removed and instead we pick up the command line flag already supported by setuptools e.g. `python setup.py bdist_wheel --py-limited-api=cp36` - and we would pass the `abi3-py36` flag to `pyo3` automatically
- [x] move wheel-building documentation from the README into a separate page of the sphinx documentation. (There are a few possibilities for wheel building, such as `build-wheels.sh` and `cibuildwheel`, so it would be nice to expand on these.)

**Comment by davidhewitt** [comment]
cc @messense what do you think about 1.0 ?

cc @alex would the proposed change to the `py_limited_api` be fine for your usage in `cryptography`? Reusing the existing command line flag seems desirable.

**Comment by messense** [comment]
Better cross compiling support code-wise or documentation-wise, possibly direct people to use [crossenv](https://github.com/benfogle/crossenv).

**Comment by alex** [comment]
When I added `py_limited_api`, I modeled it on how it works for C extensions, which is namely that you have three separate things:

- naming the `.whl`
- naming the `.so`
- and defining `PY_LIMITED_API` in C

Doing all these separately seems error prone, but I guess I don't have a strong opinion on the value of being consistent with setuptools vs. improving that UX.

**Comment by davidhewitt** [comment]
#163
