### ISSUE TITLE
Get --target, etc., from sysconfig when cross compiling

### ISSUE THREAD

**Issue by benfogle** [PyO3/setuptools-rust#138]
I am the maintainer of [crossenv](https://github.com/benfogle/crossenv), and since `cryptography` started using `setuptools-rust`, I've started receiving issues since cross compiling that package no longer works out of the box. This can be fixed by gathering more information from `sysconfig` and passing that along to rustc.

(PR incoming)

**Comment by jameshilliard** [comment]
Not sure if you're running into the exact same issue here but I'm seeing a [potentially related issue](https://github.com/PyO3/pyo3/issues/1513) when cross compiling with buildroot.

**Comment by messense** [comment]
It is indeed error-prone when invoking `bdist_wheel` with `--plat-name`.

https://github.com/messense/manylinux2014-cross-arm/runs/2199462499 here I've asked it to build `manylinux2014_aarch64` wheel and it does build the `.so` file with aarch64 gcc but named it wrong to `x86_64`.

```bash
❯ file pyo3_test.cpython-36m-x86_64-linux-gnu.so
pyo3_test.cpython-36m-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```

**Comment by benfogle** [comment]
I think that issue is common to all Python. `bdist_wheel` only uses `--plat-name` to generate the output file name, so I think you'd see this no matter what module you were trying to compile. (The other commands aren't much better: `build_ext`, for example, tells you that `--plat-name` is for cross-compiling, but it only checks it if you're running Windows.)
