### ISSUE TITLE
Possibility to disable default features

### ISSUE THREAD

**Issue by gabrik** [PyO3/setuptools-rust#142]
Hi,

I was wondering if it is possible to have a flag for disabling default features, something similar to this option in Cargo:
```
rtnetlink = { git = "https://github.com/little-dude/netlink", branch = "master", default-features = false, features = ["smol_socket"] }
```

I see there is a `feature` parameter: https://setuptools-rust.readthedocs.io/en/latest/reference.html#setuptools_rust.RustExtension but as I understand I can only add features.

Thanks

**Comment by davidhewitt** [comment]
You can do this with `RustExtension(args=["--no-default-features"])`. I'll add that as an example to the docs.
