### ISSUE TITLE
Question: `setup.py build` does not put built binary under `build/lib.*`?

### ISSUE THREAD

**Issue by futursolo** [PyO3/setuptools-rust#146]
I am trying to use poetry with `setuptools-rust` to embed some rust code in to my project.

Poetry "supports" native extensions by specifying a `build.py` scripts that modifies the arguments that's passed into `setuptools.setup`, calls `setup.py build` and then searches native extensions built by the command and adding it to wheel manually.

Currently poetry only searches `build/lib.*` for native extensions after running `setup.py build`. But `setuptools-rust` generates artifacts under `build/lib`.

See: https://github.com/python-poetry/poetry-core/blob/ae3399a5098b8a3ebd0d919ad21a7665e5a8c509/poetry/core/masonry/builders/wheel.py#L146

I have tested some projects with Cython and C extensions (`distutils.core.Extension`) and they produce files under a directory like `build/lib.macosx-10.15-x86_64-3.8` when running `setup.py build`.

I am not very familiar with the intended behaviour of `setup.py build` but the behaviour of this library seem to differ with Cython / C-exts. So I am creating this issue here. If this is the intended behaviour, feel free to close this and I will submit an issue with poetry.

**Comment by messense** [comment]
I think setuptools-rust currently puts the native extension in `build/lib`

```bash
❯ tree build
build
└── lib
    └── namespace_package
        ├── python
        │   └── __init__.py
        └── rust.abi3.so

3 directories, 2 files
```

Not sure why it's not something like `build/lib.xxx`

**Comment by messense** [comment]
> Poetry "supports" native extensions by specifying a build.py scripts that modifies the arguments that's passed into setuptools.setup, calls setup.py build and then searches native extensions built by the command and adding it to wheel manually.

Do you have an example project which I can play and test with it?

**Comment by messense** [comment]
The problem is that `build_ext` uses `build_lib` instead of `build_platlib` to put native extensions.

https://github.com/PyO3/setuptools-rust/blob/75787159051f133f24dbceeb143ee5ae976c7244/setuptools_rust/build.py#L425

https://github.com/pypa/setuptools/blob/a4dbe3457d89cf67ee3aa571fdb149e6eb544e88/setuptools/_distutils/command/build.py#L101-L108

**Comment by messense** [comment]
I guess the only workaround is to compile a dummy C extension like what milksnake does https://github.com/getsentry/milksnake/blob/ef0723e41df23d8f6357570c69c1e69cb31f9e9e/milksnake/setuptools_ext.py#L241-L259

**Comment by messense** [comment]
I've opened https://github.com/pypa/distutils/pull/43 to address this.

cc @davidhewitt
