### ISSUE TITLE
ModuleNotFoundError: No module named 'html_py_ever.html_py_ever'

### ISSUE THREAD

**Issue by spl0i7** [PyO3/setuptools-rust#148]
I was trying to use the `html_py_ever` example https://github.com/PyO3/setuptools-rust/tree/main/examples/html-py-ever however I ran into issue where it won't import the built module after building it. When I try to import it, it gives me error that 
`ModuleNotFoundError: No module named 'html_py_ever.html_py_ever'`. 

Python 3.7.3
pip 21.1.2

**Comment by spl0i7** [comment]
I used similar structure for my project, getting same issues with github actions
https://github.com/spl0i7/lzstring_pyo3/actions/runs/893566591

**Comment by davidhewitt** [comment]
Hi @spl0i7 sorry for the delay in response; I had been busy.

I see you have closed this issue, did you resolve your problem or do you still need help?

If you solved the problem, to help future users would you be willing to summarize what the issue was and what you did to solve it? Thanks.

**Comment by spl0i7** [comment]
Hello, while problem itself wasn't solved but I managed to find a work around. This issue still pops up if I install the package as `python ./setup.py install --user ` however it somehow works when using venv. 

You can actually check logs of this issue [here](https://github.com/spl0i7/lzstring_pyo3/runs/2712340289?check_suite_focus=true)
