### ISSUE TITLE
Support optional option

### ISSUE THREAD

**Issue by messense** [PyO3/setuptools-rust#15]
Just like distutils:

https://docs.python.org/3/distutils/setupscript.html#other-options

> The `optional` option is a boolean; if it is true, a build failure in the extension will not abort the build process, but instead simply not install the failing extension.

**Comment by fafhrd91** [comment]
what is your pypi username?

**Comment by messense** [comment]
@fafhrd91 It's `messense`

**Comment by fafhrd91** [comment]
I gave you permission for setuptools-rust. release process is manual at the moment

**Comment by fafhrd91** [comment]
Ok, np

**Comment by messense** [comment]
Fixed. Committed `MANIFEST.in`

**Comment by messense** [comment]
https://github.com/PyO3/setuptools-rust/blob/master/setuptools_rust/build.py#L166

If Rust is not installed, `optional` extensions won't work because `get_rust_version()` throws an uncaught exception.
