### ISSUE TITLE
v0.12.1 tag and commit missing

### ISSUE THREAD

**Issue by tiran** [PyO3/setuptools-rust#158]
The git tag v0.12.1 and release commit 0e8eb5a33bd7f3d65c43c5af77bc15f67affb1b0 are missing from this repo. Github UI shows:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by davidhewitt** [comment]
Hmm interesting, thanks for the heads-up. Not sure what happened there. I've force-pushed the tag to https://github.com/PyO3/setuptools-rust/commit/d4657b89024dc779551d8d1b1d3dc51614324828
