### ISSUE TITLE
Document how to speed up rebuilds

### ISSUE THREAD

**Issue by itamarst** [PyO3/setuptools-rust#159]
By default, `pip` runs builds from `/tmp/pip-req-build-<randomstring>`. As a result, each build is completely independent, since the `target/` directory ends up there and isn't preserved across the builds.

By adding the `--use-feature=in-tree-build` flag to `pip install`, the build happens in the main directory, much like with `cargo build`, thus enabling faster rebuilds.

**Comment by davidhewitt** [comment]
`pip` 21.3 is released which uses in-tree-builds by default, so I think there's no need to document anything here any more.
