### ISSUE TITLE
Module Install Failed - Online Dependencies

### ISSUE THREAD

**Issue by SlodeSoft** [PyO3/setuptools-rust#160]
Hi all,

I cann't install package setuptools-rust 0.12.1 fail with online connections. my environnement doesn't authorize external connection.

There is a offline package ? 

![image](https://user-images.githubusercontent.com/84590573/130212270-dcd45bdb-d0cf-4155-8d4e-1e5953b840ae.png)

Thanks !

**Comment by davidhewitt** [comment]
Can you please provide further steps how to reproduce this issue? What command are you running?

**Comment by SlodeSoft** [comment]
@davidhewitt i exec the commadn below :

sudo python3 setup.py install

**Comment by davidhewitt** [comment]
What is the operating system, python version, pip version?

**Comment by SlodeSoft** [comment]
RedHat 7.9 
python 3.6 
pip 2.1.14

**Comment by davidhewitt** [comment]
> pip 2.1.14

Can you double-check that please? That's not an actual pip version as far as I know.

Also, can you please share full logs of the command?

**Comment by SlodeSoft** [comment]
command try to get lib external i will send you logs asap

**Comment by SlodeSoft** [comment]
@davidhewitt i get this :


`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fc935930048>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fc935930860>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/setuptools-scm/`

**Comment by birkenfeld** [comment]
That is not the full command line and output. Please don't make screenshots, but copy-paste *everything* from the command line window, not only errors/warnings.

**Comment by SlodeSoft** [comment]
This is the only thing i get on screen when i exec : 

sudo python3 setup.py install
for [setuptools-rust-0.12.1]

**Comment by davidhewitt** [comment]
As birkenfeld says, we need as much information as possible to be able to help understand and resolve your issue. This means _all_ the output that `sudo python3 setup.py install` gives you, from the first log message right through the error.

In that screenshot you clip above, for example, it looks like there's an `[info]` log message immediately above, as well as a Python `Traceback` just beneath. I'm sure that these would be very useful to help us understand what steps in the program have occurred to reach the stage which fails.

**Comment by messense** [comment]
I don't think there is anything we would do if you don't have a network connection.

Instead you should download all the required packages online with `pip download some_package_name` and transfer them to the offline machine. Then install it with 
```bash
pip install --no-index --find-links /path/to/downloaded/packages/directory some_package_name
```
