### ISSUE TITLE
ModuleNotFoundError during version resolution

### ISSUE THREAD

**Issue by crockeo** [PyO3/setuptools-rust#161]
howdy folks! i think i ran into a bug when trying to install setuptools-rust from source. to reproduce:

```
$ pip install --no-binary setuptools-rust setuptools-rust
# long error message
ModuleNotFoundError: No module named 'semantic_version'
```

i think what's going on is:

1. `setuptools-rust` declares its [version as an `attr` tag](https://github.com/PyO3/setuptools-rust/blob/850fa825c804d83b946a4b925514d392d0814374/setup.cfg#L3)

1. `setuptools` attempts to [parse it statically](https://github.com/pypa/setuptools/blob/4d64156de17596dae33f2b12aaaea1d6c9327fd9/setuptools/config.py#L386-L387), fails, and falls back to [importing it normally](https://github.com/pypa/setuptools/blob/4d64156de17596dae33f2b12aaaea1d6c9327fd9/setuptools/config.py#L389-L390)

1. that `import_module` transitively imports `semantic_version` which is not available to `setuptools` since it's an install requirement, not a setup requirement (need to verify that this is why)

1. installation fails

so far i've verified this under two virtualenvs, one with python3.8 and one with python3.9. both have setuptools `57.4.0` installed.

**Comment by davidhewitt** [comment]
Hmmm, I can't reproduce this locally. Can you please share more information on the `pip` version and other packages in your environment? Also OS version, and full steps to create the virtualenv etc.

**Comment by crockeo** [comment]
this is very strange—i'm trying to reproduce it again in the same virtualenv i had before and it's no longer breaking. i think that's a good thing? e.g. running on macOS 11.5.2:

<details>
<summary>installation output</summary>

```
~/src/tmp/test-setuptools-rust$ python3.9 --version
Python 3.9.6

~/src/tmp/test-setuptools-rust$ python3.9 -m virtualenv venv
created virtual environment CPython3.9.6.final.0-64 in 454ms
  creator CPython3Posix(dest=~/src/tmp/test-setuptools-rust/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=~/Library/Application Support/virtualenv)
    added seed packages: pip==21.1.3, setuptools==57.4.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

~/src/tmp/test-setuptools-rust$ source ./venv/bin/activate

(venv) ~/src/tmp/test-setuptools-rust$ pip install --no-binary setuptools-rust setuptools-rust==0.12.1
Looking in indexes: https://pypi.lyft.net/simple/
Collecting setuptools-rust==0.12.1
  Using cached setuptools-rust-0.12.1.tar.gz (282 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting toml>=0.9.0
  Using cached https://pypi.lyft.net/api/package/toml/toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting semantic-version>=2.6.0
  Using cached https://pypi.lyft.net/api/package/semantic-version/semantic_version-2.8.5-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: setuptools>=46.1 in ./venv/lib/python3.9/site-packages (from setuptools-rust==0.12.1) (57.4.0)
Building wheels for collected packages: setuptools-rust
  Building wheel for setuptools-rust (PEP 517) ... done
  Created wheel for setuptools-rust: filename=setuptools_rust-0.12.1-py3-none-any.whl size=22068 sha256=3210680bfaa9c9e199182c97960c40b2433942e79bba0d2a26b38e1221924799
  Stored in directory: ~/Library/Caches/pip/wheels/0d/74/4c/815dea1b32e070a03f3bdebc2ac66dec872e2f4f98873de7f1
Successfully built setuptools-rust
Installing collected packages: toml, semantic-version, setuptools-rust
Successfully installed semantic-version-2.8.5 setuptools-rust-0.12.1 toml-0.10.2
```

</details>

my guess is that this has something to do with the [yanked versions of setuptools-scm](https://pypi.org/project/setuptools-scm/#history). let me troll the setuptools-scm issues to see if there's something there. either way i think it's safe to conclude this is _not_ an issue with setuptools-rust, so i'll close out this issue.

thanks for looking into this!
