### ISSUE TITLE
Split `tomlgen` into separate package?

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/setuptools-rust#163]
I'd quite like to update `setuptools_rust` to use `tomli`, which is what the rest of the pypa ecosystem is now using to parse TOML files. In particular it offers TOML 1.0 support, which the `toml` package doesn't yet offer.

However, `tomli` doesn't have write capability, so the `tomlgen` command would need to continue to use `toml` or some other package.

Also, I think the `tomlgen` command is a one-off command which might be used in development, rather than something which is necessary for end-users to build packages using `setuptools-rust`.

I'd like to propose the `setuptools-rust` 1.0 package won't include the `tomlgen` functionality. We can publish a `setuptools-rust-tomlgen` package which can be installed separately for users who want to use this to generate `Cargo.toml` files.

**Comment by messense** [comment]
I've never used `tomlgen` before, so 👍 for me.

**Comment by alex** [comment]
Fine with me

**Comment by davidhewitt** [comment]
I've started https://github.com/PyO3/setuptools-rust-tomlgen and will push a PR to remove from here later.
