### ISSUE TITLE
Using binding=Binding.Exec in Windows does not copy the .exe but the .d file

### ISSUE THREAD

**Issue by LehMaxence** [PyO3/setuptools-rust#179]
Using Windows 10, python 3.9, and helloworld example with modified setup.py to set script to False,
`python setup.py develop` copies the .d file instead of the .exe file.
Most likely because it's the first file found when looking for the executable (in build.py lines 339-346).

Also, why are executables' extensions removed?

**Comment by davidhewitt** [comment]
Thanks for reporting. Looks like this functionality is broken on windows, I've opened #182 to fix.
