### ISSUE TITLE
Link in ReadMe leads to Not Found

### ISSUE THREAD

**Issue by mlondschien** [PyO3/setuptools-rust#180]
Here: https://github.com/PyO3/setuptools-rust/blob/ba1d77e6a4f9009f26b35691485924d0a94baafc/README.md?plain=1#L80

**Comment by davidhewitt** [comment]
Sorry about this. The documentation for the 1.0 release (which this is expected to link to) is written and ready to go but thanks to various life circumstances I haven't been able to quite finish and put the release live. I'm very hopeful I can do this in the next week or so 🤞

**Comment by mlondschien** [comment]
Thanks! All good, feel free to close whenever you feel like it. I just thought I'd let you know. Thanks for working on this, looking forward to 1.0.
