### ISSUE TITLE
3.6.0 not actually supported.

### ISSUE THREAD

**Issue by Zwork101** [PyO3/setuptools-rust#183]
setuptools-rust registers itself as being compatible with 3.6.0, but is only compatible with 3.6.1

https://github.com/PyO3/setuptools-rust/blob/cf9db7cae4ea626f1310ece090f5174b6ddc4412/setup.cfg#L31

This is because it uses kwargs for `_SetupTarget` which is a named tuple.

https://github.com/PyO3/setuptools-rust/blob/cf9db7cae4ea626f1310ece090f5174b6ddc4412/setuptools_rust/build.py#L470

But kwargs were only supported in 3.6.1

https://docs.python.org/3/library/typing.html#typing.NamedTuple

> Changed in version 3.6.1: Added support for default values, methods, and docstrings.

Solution: Pass `None` in as arguments. I would submit a PR right now but I'm a bit busy, hopefully, this helps someone who had the same issue.

**Comment by davidhewitt** [comment]
I'm suprised that anyone is actually using 3.6.0, as it's so close to end-of-life and also there's so many security patches added on top of it. However I do agree this is a bug, so will add a fix. Thanks for reporting.
