### ISSUE TITLE
Script=True only support Snake Case script

### ISSUE THREAD

**Issue by williamstar** [PyO3/setuptools-rust#191]
Most of binary executable filename is `Kebab Case`, but currently is not support in `setuptools-rust`.

It seems that script name is shared with python module name from the [codebase](https://github.com/PyO3/setuptools-rust/blob/main/setuptools_rust/extension.py#L182) and python module name is not support `Kebab Case`.

For example, the origin rust_extension is `persia-embedding-parameter-server` will rename to `persia_embedding_parameter_server`.And we want to keep the original binary name but failed.

Is there any solution to fix this problem or can i propose a PR try to support `Kebab Case`?

**Comment by davidhewitt** [comment]
A PR to support `kebab-case` is very welcome 👍

**Comment by williamstar** [comment]
Ok, I will have a try. 😃

**Comment by davidhewitt** [comment]
Great! Please do ask if you have any questions about possible implementation or design.

**Comment by williamstar** [comment]
Accept a `dict` to get the script name from the target.values . I'm not sure if the design is good.

#199
