### ISSUE TITLE
cargo build target for macos arm64 in conda

### ISSUE THREAD

**Issue by adrianeboyd** [PyO3/setuptools-rust#192]
I'm running into problems with the macos arm64 build target in conda envs with `setuptools-rust>=1.0.0`. It works with v0.12.1, but with v1.0.0+ I get this error:

```none
error: Don't know the correct rust target for system type arm64-apple-darwin20.0.0. Please set the CARGO_BUILD_TARGET environment variable.
```

Setting `CARGO_BUILD_TARGET="aarch64-apple-darwin"` does work, but it's not something I can expect from my users.

Outside conda (python3.9 from homebrew):

```none
Python 3.9.6 (default, Jun 28 2021, 19:24:41) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var("HOST_GNU_TYPE")
'arm-apple-darwin20.5.0'
>>> sysconfig.get_config_var("BUILD_GNU_TYPE")
'arm-apple-darwin20.5.0'
```

In the conda env (miniforge):

```none
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:24:02) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var("HOST_GNU_TYPE")
'arm64-apple-darwin20.0.0'
>>> sysconfig.get_config_var("BUILD_GNU_TYPE")
'x86_64-apple-darwin13.4.0'
```

For reference, the particular package I'm trying to build is `spacy-alignments`, although I don't think it has any customizations that would affect the build target detection: https://github.com/explosion/spacy-alignments

**Comment by davidhewitt** [comment]
Hmm, this is a bit thorny. I think for now I'll put in a fix that simply undoes the "target detection" for this case for now. If someone needs something more clever here later, future input and PRs welcome.

**Comment by adrianeboyd** [comment]
Thanks for the quick response!
