### ISSUE TITLE
target selection issue with cibuildwheel when only arm64 or x86_64 is given

### ISSUE THREAD

**Issue by jstewmon** [PyO3/setuptools-rust#206]
👋 I was trying to build discrete x86_64 and arm64 wheels for macos (e.g. `CIBW_ARCHS_MACOS: x86_64 universal2 arm64`), but the the packaged installed from the arm64 wheel fails to load on an M1 mac with the error `(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')`.

Installing the package from the universal2 wheel works fine.

IIUC, this is a compatibility issue with cibuildwheel (we could use `CARGO_BUILD_TARGET` the "manual" way)... To be compatible, the code below should always consider the value of `ARCHFLAGS` to select the target architecture, but it currently only considers it when both x86_64 and arm64 are given (universal2).

https://github.com/PyO3/setuptools-rust/blob/258e198944f555fd85a657bb40b0e5d3f705a306/setuptools_rust/build.py#L90-L109

**Comment by davidhewitt** [comment]
Thanks for reporting. Your diagnosis sounds correct. Would you be willing to author a PR to fix this? I guess it should be a case of checking all the values in `ARCHFLAGS` and then selecting the correct Rust target as appropriate.

There's edge cases to consider, such as what to do with unrecognised flags in `ARCHFLAGS` and what if `CARGO_BUILD_TARGET` is set too. (Maybe check the two env vars are consistent?)

**Comment by jstewmon** [comment]
@davidhewitt thanks for the response. Unfortunately, I don't have the spare cycles right now to work on a PR, but the universal2 wheel meets my needs, so I'm content to use that as a workaround.

**Comment by davidhewitt** [comment]
No problem, I'm a bit swamped too at current, will try to put a PR for this together myself eventually.
