### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by A-tA-v** [PyO3/setuptools-rust#225]
Hello,

System: Ubuntu 2020, 64 bit, the latest Miniconda python environment, Python 3.7.

1) Inside conda environment, updated pip, as recommended.
2) Installed 'setuptools_rust' **using pip**, setuptools_rust version 1.30
3) Got the error: ```ModuleNotFoundError: No module named 'setuptools_rust'```
4) Tried conda installation:  ```conda install -c conda-forge setuptools-rust```
5) Same error

Eventually, fixed by this command:
``` python3 -m pip install setuptools-rust --upgrade --force --user ```
as recommened in [https://stackoverflow.com/questions/69372488/python-3-6-9-importerror-no-module-named-setuptools-rust-and-a-command-pytho](url)

The problem might be related not to this package, but to Conda itself, because I have experienced similar issues with some other packages.

**Comment by davidhewitt** [comment]
Thanks, yes it very much sounds like it was something wrong with the environment. I'm going to close this, however if you can share a reliable reproduction which shows that it was something wrong with this package I'd be happy to fix!
