### ISSUE TITLE
Allow to build without specifying a target triple

### ISSUE THREAD

**Issue by adrienballsonos** [PyO3/setuptools-rust#229]
## Description of the problem
I did not find a way to use setuptools_rust without having it passing a target triple flag (--target) to the rust compiler. The problem is that, [as explained in the rust doc](https://doc.rust-lang.org/cargo/guide/build-cache.html), using the `--target` flag changes the build directory layout and build outputs are no longer under `target/debug` or `target/release` but instead they are stored in `target/<triple>/debug/` or `target/<triple>/release/`.

In my case this is problematic because I want to share the cargo build cache and avoid re-compiling the rust library when I build the python wheel, after having built the rust library using cargo build. But to do so, I need the target dir to be `target/debug/` or `target/release/`.

**Comment by adamreichold** [comment]
Just an idea that might be helpful immediately: Maybe you can pass `--target` (matching that of the host) to your previous `cargo build` invocation as well so that the native build and the build for the wheel both end up using `$CARGO_TARGET_DIR/$TARGET/{debug,release}`.

**Comment by davidhewitt** [comment]
I very much agree with this. Perhaps we can invoke `rustc` to detect the default target and skip adding the `--target` flag if it already matches?

I'm quite busy atm so won't get around to implementing this soon, however a PR would be very welcome 👍
