### ISSUE TITLE
Working with rust-cpython

### ISSUE THREAD

**Issue by zeantsoi** [PyO3/setuptools-rust#23]
I'm working on an implementation that binds to Rust via [rust-cpython](https://github.com/dgrunwald/rust-cpython), which evidently is a [supported binding](https://github.com/PyO3/setuptools-rust/blob/master/setuptools_rust/utils.py#L16). The declaration of Python module using rust-cpython involves using a macro ([`py_module_initializer!`](https://github.com/dgrunwald/rust-cpython/blob/e2d7781433b71fe104a027d769f35d33faea575c/extensions/tests/custom_class.rs#L7)), rather than the `pyo3` method of declaring module names using Rust attributes.

As a result, I'm having some trouble writing a functioning `setup.py`. Any guidance for determining what I should pass to `RustExtension` as the name of the module?

**Comment by fafhrd91** [comment]
you should use `RustCPython` binding.

```python
RustExtension('...', 'Cargo.toml', binding=Binding.RustCPython)
```

**Comment by zeantsoi** [comment]
Right. So I _am_ using `RustCPython` as the binding for `RustExtension`

Where I get hung up is, in the following setup:

```
RustExtension('...', 'Cargo.toml', binding=Binding.RustCPython)
```

I can't quite determine what the correct _first_ argument is. For instance, if I initialize a module like so:

```
py_module_initializer!(my_module, initmy_module, PyInit_my_module, |py, m| {
    try!(m.add(py, "__doc__", "This module is implemented in Rust."));
    try!(m.add(py, "a_func", py_fn!(py, a_func(arg: String))));
    Ok(())
});
```

I would expect that my module name is `my_module`, and is importable as such within Python. However, if I pass `my_module` as the first argument to `RustExtension`, the module isn't found.

**Comment by fafhrd91** [comment]
for you case first argument should be `my_module`, or if you have some top level module then
`toplevel_mod.my_module`

**Comment by fafhrd91** [comment]
check example from old revision https://github.com/PyO3/setuptools-rust/tree/7eb26304c9475da5a042f6761439ea5c1d2b8c35

**Comment by fafhrd91** [comment]
@zeantsoi re-open if you still have questions
