### ISSUE TITLE
Allow building in locked mode

### ISSUE THREAD

**Issue by tommilligan** [PyO3/setuptools-rust#233]
`cargo` offers [the `--locked` flag](https://doc.rust-lang.org/cargo/commands/cargo-build.html#manifest-options) for reproducibility, which we use in CI to ensure we are building with the exact set of dependencies we have audited.

It would be great to have this option via `setuptools-rust`, to fail building extensions if the relevant lockfiles are out of date.

**Comment by messense** [comment]
I think you can already do it via [`args`](https://setuptools-rust.readthedocs.io/en/latest/reference.html#setuptools_rust.RustExtension):

```python
from setuptools import setup
from setuptools_rust import Binding, RustExtension

setup(
    name="hello-rust",
    version="1.0",
    rust_extensions=[RustExtension("hello_rust.hello_rust", binding=Binding.PyO3, args=["--locked"])],
    packages=["hello_rust"],
    # rust extensions are not zip safe, just like C-extensions.
    zip_safe=False,
)
```

**Comment by tommilligan** [comment]
:facepalm: of course there's a generic solution built in. Well, it was a good exercise in learning how the project works!

Thanks, closing

**Comment by messense** [comment]
> It is important this is supported in all callsites (not just in build), as all cargo calls have the potential to update the lockfile - for instance, cargo metadata will do so, which we call before cargo build when compiling the extension.

Well I'm not sure if `args` correctly handles this though.

**Comment by tommilligan** [comment]
Yes, I think you're right. I just tried this out, and I think because args are only forwarded to `build`, not e.g. `metadata`, the lockfile is updated before build is called.

I'm not sure what you'd prefer:
- forwarding all args to all cargo calls (not sure if all args will be supported by all invocations
- doing some sort of filtering logic 'if `--frozen` was passed, pass it along to `metadata` as well'
- just the first class support, as initially proposed

**Comment by messense** [comment]
> forwarding all args to all cargo calls (not sure if all args will be supported by all invocations

This will certainly running into unsupported args issue.

> doing some sort of filtering logic 'if --frozen was passed, pass it along to metadata as well'

I'd prefer this but I'm not opposed to do the third option.

> first class support for frozen=True, as initially proposed the the linked PR

Note that technically it's possible that user also passes `--locked` in `args`, and cargo doesn't like duplicated `--locked` argument:

```bash
cargo build --locked --locked
error: The argument '--locked' was provided more than once, but cannot be used multiple times

USAGE:
    build [OPTIONS]

For more information try --help
```

**Comment by tommilligan** [comment]
> Note that technically it's possible that user also passes `--locked` in `args`, and cargo doesn't like duplicated `--locked` argument:

That is possible, but a new `frozen` argument would be opt-in, and so wouldn't break for any existing usages.

You could also argue the same for `debug=False` and `args=["--release"]`, which will result in a duplication of the `--release` flag.

I would prefer to add first class support in this case, because:

- There is some additional logic required at the application layer (for instance, for the `vendor` call, aggregating the `frozen` state from potentially many extensions)
- It provides an opportunity to document this as a feature we've thought about, in an appropriate place
- As you point out, the `args` feature doesn't currently support this, and it feels like adding string forwarding etc. on top of it is not a clean solution. I would be inclined to update the documentation to clarify that `args` is only passed to the `cargo build` command, not every cargo command issued.

If you strongly preferred the `args`-type solution, I would probably lean towards implementing a `global_args`, which is a separate array passed to every `cargo` call. This would be generic over `--frozen`, `--locked` etc., but I'm not totally sold that's a nice idea.

**Comment by tommilligan** [comment]
It's worth pointing out the cargo has a section for [`Manifest Options`](https://doc.rust-lang.org/cargo/commands/cargo-build.html#manifest-options), which are:

- `--manifest-path`: already set by setuptools-rust
- `--frozen`
- `--locked`: what this issue was originally raised for
- `--offline`

A solution that was generic over `--frozen`, `--locked` and `--offline` might be nice, but could also be pre-optimization.

**Comment by messense** [comment]
As I said I'm not opposed to add first class support, let's do that now. I'm just a little worried that we'll grow more and more arguments for `RustExtension`.

**Comment by tommilligan** [comment]
Okay, great. I've reopened #234 and CI is green on it, so just let me know any tidy-ups needed.
