### ISSUE TITLE
rustc_flags applied only to top-level crate

### ISSUE THREAD

**Issue by cassiersg** [PyO3/setuptools-rust#235]
When `rustc_flags` are given to `RustExtension`, these flags are used only to build to top-level crate, and not the dependencies (at least for cdylib builds). This is due to using `cargo rustc` as build command, instead of using `cargo build` while setting the `RUSTFLAGS` environment variable (see https://doc.rust-lang.org/cargo/commands/cargo-rustc.html).

Is this behavior a bug ? If not, would you welcome a PR for an additional flag that would be applied to all crates built ?

As an example, my use-case is the flag `-C target-feature=+avx2`, which has to be applied to the dependencies.

**Comment by davidhewitt** [comment]
Hi, sorry for the slow reply. I agree this is a bug, a PR would be very welcome!

**Comment by davidhewitt** [comment]
I had a further thought about this and decided that it's possible there are valid use cases for `rustc_flags`, so I decided against changing them.

In #260 I documented this behavior and suggest using `RUSTFLAGS` as above. If an environment variable is inconvenient you can always have a `.cargo/config` file to set flags.
