### ISSUE TITLE
Release v1.4.0

### ISSUE THREAD

**Issue by messense** [PyO3/setuptools-rust#255]

**Comment by davidhewitt** [comment]
Yes! I was sort of waiting for #240 / #244, however it now looks like we don't need to change `setuptools-rust` once the upstream fixes go in.

Let's get #254 merged and then release?

**Comment by davidhewitt** [comment]
(Just pushed a tiny follow-up in #256 and then let's put this live.)

**Comment by sumitkanoje** [comment]
What is the planned release date? waiting to use `RunBin` feature

**Comment by davidhewitt** [comment]
At the weekend I'll push a fix for #235 (and I think I'll probably deprecate the `native` option to `RustExtension` at the same time) and then release once that's in.

**Comment by h-vetinari** [comment]
Woohoo! 🥳 

Conda-forge PR is ready too: https://github.com/conda-forge/setuptools-rust-feedstock/pull/22
