### ISSUE TITLE
Better error when compiled artifacts are in use

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/setuptools-rust#257]
I was thinking the other day it might be nice to check if any processes are using the installed extension before attempting to copy across.

I think on Windows we'll get an `OsError` raised during copy, and on Unix any running processes are just likely to crash when they next need to load a segment of the native code.

Doing a check and raising our own friendly error might be nicer UX.

**Comment by adamreichold** [comment]
> I think when I've seen segfaults before it was for libraries rather than executables. Might behave differently?

I think this mostly happens because updates are not transactional, e.g. an older executable will after having been started dynamically load a newer library that has an different ABI the older version of the library. But as written above, `ETXTBSY` was never completely reliable.

**Comment by davidhewitt** [comment]
From the article you linked above:

> The MAP_DENYWRITE flag was created for just this use case, so that shared libraries could not be written while in use. When MAP_DENYWRITE went away, so did that protection; current Linux systems will happily allow a suitably privileged user to overwrite in-use, shared libraries. 

It really does sound to me like shared libraries don't get `ETXTBSY` protection 😊

**Comment by adamreichold** [comment]
Indeed, the removal seems to be further along than I remembered from reading the article. Appears like I did not read it very thoroughly. 😊

**Comment by adamreichold** [comment]
So for extensions modules which are shared libraries `ETXTBSY` is irrelevant. Sorry for the noise...

**Comment by davidhewitt** [comment]
Not at all! Always worth sharing information and debating my spurious claims of segfaults 😂
