### ISSUE TITLE
Invalid version string

### ISSUE THREAD

**Issue by moubctez** [PyO3/setuptools-rust#262]
Getting Rust version produces incorrect result:

```
  File "/dist/pkg/lib/python3.10/site-packages/setuptools_rust/rustc_info.py", line 13, in get_rust_version
    return Version(_rust_version_verbose().split(" ")[1])
  File "/dist/pkg/lib/python3.10/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/dist/pkg/lib/python3.10/site-packages/semantic_version/base.py", line 318, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '1.62.0\nbinary:'
```

That's because the output of `rustc -Vv` is being split by a single space (" "), and the new-line character stays.

I had to fix it with this patch:

```
--- setuptools_rust/rustc_info.py.orig	2022-07-05 06:20:44.000000000 +0000
+++ setuptools_rust/rustc_info.py
@@ -10,7 +10,7 @@ def get_rust_version() -> Optional[Versi
     try:
         # first line of rustc -Vv is something like
         # rustc 1.61.0 (fe5b13d68 2022-05-18)
-        return Version(_rust_version_verbose().split(" ")[1])
+        return Version(_rust_version().split(" ")[1])
     except (subprocess.CalledProcessError, OSError):
         return None
 
@@ -59,5 +59,10 @@ def get_rust_target_list() -> List[str]:
 
 
 @lru_cache()
+def _rust_version() -> str:
+    return subprocess.check_output(["rustc", "-V"], text=True)
+
+
+@lru_cache()
 def _rust_version_verbose() -> str:
     return subprocess.check_output(["rustc", "-Vv"], text=True)
```

**Comment by shernshiou** [comment]
> Getting Rust version produces incorrect result:
> 
> ```
>   File "/dist/pkg/lib/python3.10/site-packages/setuptools_rust/rustc_info.py", line 13, in get_rust_version
>     return Version(_rust_version_verbose().split(" ")[1])
>   File "/dist/pkg/lib/python3.10/site-packages/semantic_version/base.py", line 105, in __init__
>     major, minor, patch, prerelease, build = self.parse(version_string, partial)
>   File "/dist/pkg/lib/python3.10/site-packages/semantic_version/base.py", line 318, in parse
>     raise ValueError('Invalid version string: %r' % version_string)
> ValueError: Invalid version string: '1.62.0\nbinary:'
> ```
> 
> That's because the output of `rustc -Vv` is being split by a single space (" "), and the new-line character stays.
> 
> I had to fix it with this patch:
> 
> ```
> --- setuptools_rust/rustc_info.py.orig	2022-07-05 06:20:44.000000000 +0000
> +++ setuptools_rust/rustc_info.py
> @@ -10,7 +10,7 @@ def get_rust_version() -> Optional[Versi
>      try:
>          # first line of rustc -Vv is something like
>          # rustc 1.61.0 (fe5b13d68 2022-05-18)
> -        return Version(_rust_version_verbose().split(" ")[1])
> +        return Version(_rust_version().split(" ")[1])
>      except (subprocess.CalledProcessError, OSError):
>          return None
>  
> @@ -59,5 +59,10 @@ def get_rust_target_list() -> List[str]:
>  
>  
>  @lru_cache()
> +def _rust_version() -> str:
> +    return subprocess.check_output(["rustc", "-V"], text=True)
> +
> +
> +@lru_cache()
>  def _rust_version_verbose() -> str:
>      return subprocess.check_output(["rustc", "-Vv"], text=True)
> ```

I can confirm this patch works. Can you submit a pull request to solve it? Thanks

**Comment by ostefano** [comment]
Fix works here are as well.

New release would be nice because `setuptools-rust` is used by `pipenv` at build time (so hot-patching not trivial).
