### ISSUE TITLE
Msys2 + Mingw (Windows GNU) builds broken with 1.4.0+

### ISSUE THREAD

**Issue by theCapypara** [PyO3/setuptools-rust#266]
setuptools-rust 1.4.0 has broken compatibility with building for `*-pc-windows-gnu` (Rust) / `cp*-cp*-mingw_*` (Python).

The reason for this is that it now looks for a built `.so` file after compiling the Rust code instead of a `.dll`.

Example of a failing build: https://github.com/SkyTemple/skytemple-rust/runs/7265998186?check_suite_focus=true

**Comment by davidhewitt** [comment]
Hmm, will try to add mingw CI in #267

**Comment by davidhewitt** [comment]
Fixed in #267
