### ISSUE TITLE
support UniFFI bindings

### ISSUE THREAD

**Issue by tomtau** [PyO3/setuptools-rust#270]
https://github.com/mozilla/uniffi-rs
Python bindings can be generated via:
` uniffi-bindgen generate [...path to the UDL file...] --config uniffi.toml --language python --out-dir [...output path...]`

sample toml config: https://github.com/mozilla/uniffi-rs/blob/e7ff0dafda31d413ba94065c2f7039166ae03e94/examples/custom-types/uniffi.toml#L26

**Comment by davidhewitt** [comment]
Thanks for the suggestion! I don't have the capacity to implement this myself right now, would accept a PR from anyone who wants this 👍

**Comment by messense** [comment]
FYI, I've added UniFFI bindings support in maturin v0.14: https://github.com/PyO3/maturin/pull/1275.

For setuptools-rust you can already wrap UniFFI bindings via `NoBinding`, for example https://github.com/bitcoindevkit/bdk-ffi/blob/3edda27ef25a254b9bce977ea79500e57dfcecf0/bdk-python/setup.py#L54-L58

**Comment by davidhewitt** [comment]
I think as `maturin` has this, and also there is a workaround via `NoBinding`, I'm going to close this as unnecessary.
