### ISSUE TITLE
Locating executable does not work properly

### ISSUE THREAD

**Issue by YongjunHe** [PyO3/setuptools-rust#281]
Version: 6d87a5bbaa49d9d7d06e735445011c30c0473132
setuptools_rust/build.py line 258-267

Though executables indeed exist in the directory, the StopIteration throws an Error unproperly.

**Comment by davidhewitt** [comment]
@YongjunHe can you provide a bit more about your environment to reproduce this? We test it on CI and it works fine, so there must be something unique about your build output.

**Comment by YongjunHe** [comment]
@davidhewitt Thanks for the quick reply. I built multiple executables in one directory but here will throw an error even though one of the executables matches the [if condition](https://github.com/PyO3/setuptools-rust/blob/main/setuptools_rust/build.py#L262). I downgraded it to 1.4.1 and it can work well now.

**Comment by davidhewitt** [comment]
Can you give any examples of the output or debug the code? I will not make any changes without further information.

**Comment by YongjunHe** [comment]
In my case, it built executables persia-embedding-parameter-server and persia-embedding-worker under rust/target/release/ and then out the below information.

      warning: `persia-embedding-server` (bin "persia-embedding-parameter-server") generated 1 warning
          Finished release [optimized] target(s) in 5m 00s
      error: Rust build failed; unable to locate executable 'persia-embedding-parameter-server'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for persia
Failed to build persia
ERROR: Could not build wheels for persia, which is required to install pyproject.toml-based projects

**Comment by davidhewitt** [comment]
Right, looks like the repo is https://github.com/PersiaML/PERSIA, I'll take a look.

**Comment by YongjunHe** [comment]
Thank you.

**Comment by davidhewitt** [comment]
Found a fix in #283. Thanks for reporting!
