### ISSUE TITLE
1.5.x sdist no longer contains examples, docs, and tests

### ISSUE THREAD

**Issue by tiran** [PyO3/setuptools-rust#285]
The source distributions for 1.5.0 and 1.5.1 no longer contain docs, examples, and tests directories. The tests and examples are useful for downstream packagers. For example I use them in Fedora packages to verify that setuptools-rust is working correctly.

Could you please re-add them? I'm not sure why they are now omitted from sdist. You may have to add the directories to `MANIFEST.in`.

**Comment by davidhewitt** [comment]
Ungh, must be something different in the build environment. I'm prioritising the PyO3 0.17 release first, I'll investigate this in a week or two and push 1.5.3. If you need it sooner a PR to help things along is appreciated 🙂

**Comment by tiran** [comment]
Which ``MANIFEST.in`` do you prefer,
```
graft examples
recursive-include tests *.py
```
or
```
recursive-include examples *.py *.rs *.toml *.ini *.cfg *.sh *.lock *.in *.txt *.html *.md *.yml Dockerfile
recursive-include tests *.py
```
?

**Comment by davidhewitt** [comment]
Probably better to go for `recursive-include` so that we don't accidentally ship build products etc? Has the downside of needing to opt-in to example contents though.

**Comment by davidhewitt** [comment]
>  I'm not sure why they are now omitted from sdist.

On further reading, I think what happened is we stopped using `setuptools_scm` - I'll see if I can make it used only in sdist step.

**Comment by davidhewitt** [comment]
Yes, it looks like just installing `setuptools-scm` for the sdist step is enough to fix the sdist. Thanks for reporting, I'll push 1.5.2 later today.
