### ISSUE TITLE
Is there a way to trigger `release` target build for `build_ext --inplace` command?

### ISSUE THREAD

**Issue by lycantropos** [PyO3/setuptools-rust#293]
I find it useful that `build_ext --inplace` command copies artifacts into target destination, but by default `setuptools-rust` builds `dev` target, is there a way (e.g. using some environment variable) to switch to `release` target?

Thanks in advance.

**Comment by davidhewitt** [comment]
Maybe `setup.py build_rust --release` ?

**Comment by davidhewitt** [comment]
Although I'm tempted to suggest this might be better served by `maturin develop --release`, as `setup.py` as an entry point is deprecated so I've been considering dropping the `build_rust` subcommand. (#259)

You can also achieve this yourself by writing custom logic in your `setup.py` which sets `args` for your `RustExtension`.

**Comment by lycantropos** [comment]
@davidhewitt: thanks, `build_rust --release --inplace` works
