### ISSUE TITLE
can I build an `.so` without the target between the module name and the extension?

### ISSUE THREAD

**Issue by mooreniemi** [PyO3/setuptools-rust#312]
I have a bit of an esoteric case: I want to run a PySpark job that depends on a Python library that uses PyO3 to bind a Rust library.

In AWS Glue, where I run this PySpark job, it doesn't work because Spark throws an error if there is an extra `.` in the file path name. Eg.

```bash
# this fails because of the .
my_python_module.cpython-37m-x86_64-linux-gnu.so
# this succeeds
my_python_module.so
```

I *think* that the target is added into the `.so` path by PyO3 setuptools-rust because [of this documentation mention](https://pyo3.rs/v0.16.4/building_and_distribution) (see below quote, I know it's `whl` but this might apply to `so`?) but I haven't found where yet, or how to turn it off.

> maturin and setuptools-rust will give the wheel a name like my-extension-1.0-cp37-abi3-manylinux2020_x86_64.whl.

I can `mv` my `.so` after build in a custom build wrapper script to fix the above, but it "feels wrong" to me that I can't set this directly. Any idea where this setting might be and how it can be toggled off?

**Comment by davidhewitt** [comment]
What error does Spark throw? Have you got an example of how this works with a C-based extension?

If memory recalls correctly, we don't generate this filename ourselves, instead we ask `setuptools` upstream to generate it for us: https://github.com/PyO3/setuptools-rust/blob/0926da89f3ec504a32a9137446151dd296f12c29/setuptools_rust/build.py#L386

**Comment by davidhewitt** [comment]
Will close as no response in 6 months.
