### ISSUE TITLE
Facing an issue while trying to build setuptools-rust

### ISSUE THREAD

**Issue by abhinavbandaru** [PyO3/setuptools-rust#314]
Hi.

I'm facing this error while trying to build setuptools-rust:
`ninja: error: unknown target 'install'`

The command being used is this:
2023-02-14 02:21:58 gobuilds.Compile : 02:21:58.223 sh_tools   INFO     /build/mts/release/sb62854717/compcache/cayman_ninja/ob-20724186/macosx-elcapitan/bin/mac64/ninja install -j4 -v

Could you please help me understanding why this is happening and how i can resolve it?

**Comment by davidhewitt** [comment]
Why are you trying to use ninja to build this? `setuptools-rust` is just a Python package. Use `pip install setuptools-rust`.

**Comment by abhinavbandaru** [comment]
My company requires me to add a security layer (cayman) before we can consume it, hence I cannot pip install :/
Should we not use ninja to build this? Are you suggesting we use cmake instead?

**Comment by messense** [comment]
It's hard to answer your question without clarifying what `cayman` does and why did you use `ninja` and its configuration (the `.ninja` file you used).
