### ISSUE TITLE
Python crashes on import when using pip editable install on M1

### ISSUE THREAD

**Issue by drdavella** [PyO3/setuptools-rust#326]
Python version: 3.10.10
Platform: macOS-12.6.3-arm64-arm-64bit

From the installation command:
```
  Successfully installed semantic-version-2.10.0 setuptools-67.6.1 setuptools-rust-1.5.2 typing-extensions-4.5.0 wheel-0.40.0
  Installing build dependencies ... done
```

Here's my `RustExtension` definition:
```python
    rust_extensions=[
        RustExtension(
            "mypackage.bindings._corelib",
            "src/rust/Cargo.toml",
            binding=Binding.PyO3,
            py_limited_api=True,
            rust_version=">=1.56.0",
            features=["pyo3/abi3-py37"],
        )
    ],
```

The following causes Python to crash with error code 137 when I install my package with `pip install -e`:
```python
from mypackage.bindings import _corelib
```

However it works just fine with a normal install.

I'm unclear whether this is specific to my platform or not. FWIW, I'm also using miniconda.

This is nearly identical to an issue described on StackOverflow: https://stackoverflow.com/questions/72158029/pyo3-rust-module-kills-python-on-import

**Comment by davidhewitt** [comment]
Sorry for the slow reply. Would you be willing to push your project with instructions as a minimal repro? I just tested on my M1 Mac and don't get crashes with `pip install -e`.

**Comment by drdavella** [comment]
@davidhewitt no problem at all. Here's a package that minimally reproduces for me: https://github.com/drdavella/rust-extension. I'm installing from within that directory using `pip install -e .`.

Oddly, changing the number of `println` statements in the `print_hello` function seems to change the behavior _on import_. If I delete one of the statements the import works fine. This is all very strange to me and it's possible that I've just done something silly.

**Comment by davidhewitt** [comment]
Definitely working fine for me. Here's the instructions I'm running:

```
conda create -n str-326 python=3.10
conda activate str-326
pip install -e .
python -c "import mypackage.bindings._corelib; mypackage.bindings._corelib.print_hello()"
```

I just get the expected prints, and can edit the statements and recompile with `pip install -e` again fine. What rust compiler are you using? Sounds more like a miscomputation than anything else.

**Comment by drdavella** [comment]
It looks like I was using an older version of nightly from October, but even when I updated to latest (`rustc 1.70.0-nightly (9df3a39fb 2023-04-11)`) I have the same problem. Just as a sanity check, is there a way to verify which version is getting picked up by `setuptools-rust`? I don't see it in the output with `pip -vv install -e .`

**Comment by drdavella** [comment]
Alright after a bit more investigation, it looks like this is a problem with System Integrity Protection on M1 and not a problem with `setuptools-rust` itself. I was able to resolve the issue with the following command:
```
$ codesign --sign - src/mypackage/bindings/_corelib.abi3.so
```

I found a similar issue here https://github.com/nodejs/node/issues/40827.

Just adding documentation in case anyone else encounters this issue. I'm not sure whether there's a way to address this on your end, but please feel free to close. Thanks for your help.

**Comment by davidhewitt** [comment]
Ah, that makes sense. Thanks for sharing the solution here!
