### ISSUE TITLE
Unable to control `--debug` / `--release` via PEP517 backend

### ISSUE THREAD

**Issue by mgorny** [PyO3/setuptools-rust#327]
Unless I'm mistaken, there is no way to pass `--debug` / `--release` argument to `build_rust` when building via the PEP517 backend.

**Comment by davidhewitt** [comment]
I think you're correct. Unless things have changed, I don't think PEP517 gives a mechanism to pass arguments to the build backend in general.

This was solved in `maturin` with `MATURIN_PEP517_ARGS` env var. See https://github.com/PyO3/maturin/pull/786

I'd accept a PR to achieve a similar control via env var here, though the design might be a bit different.

**Comment by mgorny** [comment]
> I think you're correct. Unless things have changed, I don't think PEP517 gives a mechanism to pass arguments to the build backend in general.

Actually, PEP517 provides a `config_settings` dict that can be used to pass options to the backend. However, I don't think that setuptools provides a way for plugins to utilize it.

That said, I'm not really sure because the code is very complex and unreadable to me.

**Comment by davidhewitt** [comment]
Hmm, reading around a little, I think we can try to support something like

`python -m build -C--build-option=--rust-debug`

Looks like all PEP517 arguments to setuptools builds must go under the `--build-option` and `--global-option` namespaces like this.

**Comment by mgorny** [comment]
Thinking about it, I'd prefer environment variable approach — if only because it means we can set it globally and not have to worry whether the package in question uses setuptools-rust or not.

**Comment by davidhewitt** [comment]
Since 1.8.0 we now have `SETUPTOOLS_RUST_CARGO_PROFILE`, which should meet this need.

Note that for `--debug`, the profile is called `dev`, i.e. `SETUPTOOLS_RUST_CARGO_PROFILE=dev`. (This was a choice made by `cargo` for a reason which I am not privy to.)

**Comment by mgorny** [comment]
Thanks! FWICS, maturin uses `dev` also, so that's consistent.

**Comment by davidhewitt** [comment]
Yes I think `maturin` also inherited this from cargo.
