### ISSUE TITLE
No module named 'setuptools.command.build'

### ISSUE THREAD

**Issue by otakutyrant** [PyO3/setuptools-rust#328]
Many people complain that they encounter this error when they try to install [transformers or whisper](https://github.com/UKPLab/sentence-transformers/issues/1652), and an workaround is to install them through pip immediately.

I encountered this error too when I tried to install whisper. And I found out that the `setuptools-rust` module seems do not work individually even:

```
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools.command.build import build
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools.command.build'
>>> import setuptools_rust
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/setuptools_rust/__init__.py", line 1, in <module>
    from .build import build_rust
  File "/usr/lib/python3.10/site-packages/setuptools_rust/build.py", line 23, in <module>
    from setuptools.command.build import build as CommandBuild  # type: ignore[import]
ModuleNotFoundError: No module named 'setuptools.command.build'
>>> from setuptools_rust import Binding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/setuptools_rust/__init__.py", line 1, in <module>
    from .build import build_rust
  File "/usr/lib/python3.10/site-packages/setuptools_rust/build.py", line 23, in <module>
    from setuptools.command.build import build as CommandBuild  # type: ignore[import]
ModuleNotFoundError: No module named 'setuptools.command.build'
```

I use Arch Linux and [the Arch Linux package itself](https://archlinux.org/packages/community/any/python-setuptools-rust/).

**Comment by felixonmars** [comment]
```
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools.command.build import build
>>> import setuptools_rust
>>>
```

Cannot reproduce here. Do you happen to have `setuptools` installed via pip and didn't update?

**Comment by otakutyrant** [comment]
My bad. I imported setuptools and found out its `__file__` was `'/home/otakutyrant/.local/lib/python3.10/site-packages/setuptools/__init__.py'`. I didn't know I had this local setuptools package even.

I uninstalled it and reinstalled `python-setuptools-rust`. The issue is fixed. @felixonmars You have my gratitude from the bottom of my heart.
