### ISSUE TITLE
Can not build up example code

### ISSUE THREAD

**Issue by yanganto** [PyO3/setuptools-rust#34]
I got a problem to build up the example code.

If someone has any idea, please kindly tell me.

Thank you.

Environment:
python 3.6.5
rustup 1.11
rustc 1.27.0-nightly
cargo 1.27.0-nightly

$ python setup.py build

error: expected one of `(` or `<`, found `"_helloworld"`
 --> src/lib.rs:9:1
  |
9 | #[modinit("_helloworld")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `hello-world`.

**Comment by konstin** [comment]
Thanks for reporting this!

The cause for this is that the quotation marks were a temporary workaround for a breaking change in in nightly rust. The release of pyo3 0.2.7 made that workaround obsolete and thereby broke the example. I fixed the example in ec8d8ab.
