### ISSUE TITLE
Allow offline mode via environment variable

### ISSUE THREAD

**Issue by theCapypara** [PyO3/setuptools-rust#363]
Hello! I'm trying to publish an app using Flatpak. Flatpak works with completely offline builds where all artifacts are pre-fetched and no internet connection is available in the build environment,

At the moment (as far as I can tell) `setuptools_rust` requires the `--offline` flag for Cargo to be placed in the setup.py of the project that uses it. As such I'm currently forced to write and include patches to all packages using Setuptools Rust.

It would be great if offline mode could be enforced using an environment variable, ideally one shared with Maturin, see this issue:
https://github.com/PyO3/maturin/issues/1784

**Comment by theCapypara** [comment]
Maturin uses `config-settings`, setuptools-rust could probably do the same.

**Comment by davidhewitt** [comment]
The most portable way seems to be to send a PR to `cargo` to support `CARGO_OFFLINE` directly, if you're open to that?

**Comment by davidhewitt** [comment]
Alternatively maybe something like https://github.com/PyO3/setuptools-rust/issues/327#issuecomment-1524960935 using the config settings.

**Comment by theCapypara** [comment]
If `CARGO_OFFLINE` would be OK I'd be interested in giving implementing this a try.

I think this sounds like the easiest and also most expected solution. It's also really easy to implement in any CI pipeline (such as Flatpak manifests) without needing to reach into the requirements of the package that uses setuptools-rust (given that pip doesn't strip environment variables... not sure if it does with build isolation).

**Comment by davidhewitt** [comment]
Actually now that I look at this again I realise what you want is already present - setting `CARGO_NET_OFFLINE=true` should set offline mode.

See https://doc.rust-lang.org/cargo/reference/config.html#netoffline

**Comment by theCapypara** [comment]
Oh, really?
I looked for an option like this. Now it's been a short while, but I wonder how I missed this, or if I tried and it didn't work. I'll try again and update.

**Comment by theCapypara** [comment]
This does indeed work, thank you!

If anybody needs a reference: https://github.com/flathub/org.skytemple.Randomizer/commit/2b3d4cea83eb3b614b326a0372bf78e14763be7a#diff-3e722fa1f0525d390439912146aef963826ca681721f98919ae5d98910855071R197-R240
