### ISSUE TITLE
With latest nightly rust, builds failing due to changes in cargo output

### ISSUE THREAD

**Issue by alex** [PyO3/setuptools-rust#398]
I'm currently seeing all builds failing on the latest nightly Rust with:

```
  error: Rust build failed; unable to find any cdylib or dylib build artifacts
```

This error comes from: https://github.com/PyO3/setuptools-rust/blob/main/setuptools_rust/build.py#L301-L310

The cause appears to be that the format of the `package_id` variable changed. On stable, `package_id` for me is: `cryptography-rust 0.1.0 (path+file:///Users/alex_gaynor/projects/cryptography/src/rust)`, while on nightly, the `package_id` is `path+file:///Users/alex_gaynor/projects/cryptography/src/rust#cryptography-rust@0.1.0`.

However, the format of package IDs found in the cargo JSON build output is unchanged, which results in `_find_cargo_artifacts` no longer matching things.

I'm not sure if this is a cargo bug or a setuptools-rust bug.

**Comment by alex** [comment]
Actually, more likely https://github.com/rust-lang/cargo/pull/12914

**Comment by alex** [comment]
It looks like these landed in rustc in seperate bumps:

- https://github.com/rust-lang/rust/pull/120036
- https://github.com/rust-lang/rust/pull/120071

And I believe these were split across separate nightlies, so it is possible this will be resolved in the next nightly bump.

**Comment by davidhewitt** [comment]
This is also affecting `maturin`, I guess we see if it resolves again tomorrow then?

**Comment by alex** [comment]
That's my plan

**Comment by alex** [comment]
Ok we're good with the nightly that came out a few minutes ago. Declaring victory here.
