### ISSUE TITLE
Trouble using pyproject.toml for limited api

### ISSUE THREAD

**Issue by krpatter-intc** [PyO3/setuptools-rust#399]
```
python setup.py bdist_wheel --py-limited-api=cp38
```

Seems to work fine, but I try to use `python -m build` where the toml is configured with the extension, then it doesn't build with the limited api.

```
[[tool.setuptools-rust.ext-modules]]
target = "mytarget"
py-limited-api = true
```

I put a breakpoint down in the code, and this is the point where I can tell there is a difference and the cmd_obj ends up with `cmd.py_limited_api = False` using `build` only, but in the working case it is `cp38`

```python

def _get_bdist_wheel_cmd(  # type: ignore[no-any-unimported]
    dist: Distribution, create: bool = True
) -> Optional[CommandBdistWheel]:
    breakpoint()
    try:
        cmd_obj = dist.get_command_obj("bdist_wheel", create=create)
        cmd_obj.ensure_finalized()  # type: ignore[union-attr]
        return cast(CommandBdistWheel, cmd_obj)  # type: ignore[no-any-unimported]
    except Exception:
        return None

```

**Comment by davidhewitt** [comment]
Thanks for the report, I'll try to take a look in the coming days.

> it doesn't build with the limited api

Can I check what you're doing to determine to verify that?

**Comment by krpatter-intc** [comment]
The resulting .whl with `python setup.py bdist_wheel --py-limited-api=cp38` is:

`mytarget-0.0.1-cp38-abi3-win_amd64.whl`

But with `python -m build` it is still:

`mytarget-0.0.1-cp39-cp39-win_amd64.whl`

**Comment by davidhewitt** [comment]
Ah I see. Probably what is happening is that the Rust build _is_ using the limited API but the `bdist_wheel` command isn't, so that's why the wheel name is wrong.

You could try creating a file, point the `DIST_EXTRA_CONFIG` environment variable at it, and set `bdist_wheel` to use the limited API in that file.

For example we do this in CI at https://github.com/PyO3/setuptools-rust/blob/58266f2272820ab30e05b80f962bf7966d578a4c/.github/workflows/ci.yml#L164

Probably we need to update some documentation

**Comment by krpatter-intc** [comment]
I tried a few variations on that: (i'm on windows)

```
set DIST_EXTRA_CONFIG=[bdist_wheel]\npy_limited_api=cp39
python -m build -w --config-setting=--py-limited-api=cp38 --no-isolation
```
but so far no luck

also tried directly putting the setting in to the toml:

```
[bdist_wheel]
py-limited-api = "cp39"
py_limited_api = "cp39"
```

**Comment by krpatter-intc** [comment]
I looked through that example and the test, and the main difference between what I have and that test is that I have 100% pyproject.toml (well...i have `setuptools.setup()` but that's it)

**Comment by krpatter-intc** [comment]
I misunderstood that the line was creating and new file for setup.cfg during the build. Yes,  creating and making a new setup.cfg fixed it, or for folks doing just a pyproject.toml, the trick is to add:

```
[tool.distutils.bdist_wheel]
py_limited_api = "cp38"
```

**Comment by krpatter-intc** [comment]
Submitted #400 to document

**Comment by davidhewitt** [comment]
Closing as we've documented a few solutions now between these issues, PRs and the README. Thanks again!
