### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by craftyguy** [PyO3/setuptools-rust#40]
Hi! I would like to package this for Arch Linux's AUR, but there is no clear indication of the license this software is released under. PyPi lists it as MIT but I just want to confirm.

**Comment by marcelotrevisani** [comment]
There is a request in ``conda-forge`` as well and we need to know what is the license of this project. If possible, please add the license into the project and add in``MANIFEST.in``

**Comment by marcelotrevisani** [comment]
cc: @konstin

**Comment by craftyguy** [comment]
FYIY, the [setup.py does mention the MIT license](https://github.com/PyO3/setuptools-rust/blob/master/setup.py#L17), but it would be great to have the license explicitly included in MANIFEST.in or a LICENSE file.

**Comment by marcelotrevisani** [comment]
I opened a PR for that
https://github.com/PyO3/setuptools-rust/pull/41

**Comment by craftyguy** [comment]
Awesome, thanks @marcelotrevisani !
