### ISSUE TITLE
Please update PyO3 to 0.20.3

### ISSUE THREAD

**Issue by mgorny** [PyO3/setuptools-rust#411]
Could you update PyO3 to 0.20.3 and make a new release, please? The current version prevents us from running the test suite on PowerPC (per https://github.com/PyO3/pyo3/pull/3882/commits/9d1b11f70459367593e4cb92919f5f98c156dda9).

**Comment by davidhewitt** [comment]
Done! 👍

**Comment by mgorny** [comment]
Thanks a lot!
