### ISSUE TITLE
Tag for release 0.10.5

### ISSUE THREAD

**Issue by marcelotrevisani** [PyO3/setuptools-rust#42]
Could you please create a tag for version ``0.10.5``? That would be good! :)

**Comment by marcelotrevisani** [comment]
cc: @konstin

**Comment by konstin** [comment]
Done: https://github.com/PyO3/setuptools-rust/releases/tag/v0.10.5

**Comment by marcelotrevisani** [comment]
Thanks @konstin , I'm going to close this issue then
