### ISSUE TITLE
Failing compilation on MINGW + msys2 when `poetry install`

### ISSUE THREAD

**Issue by y-yu** [PyO3/setuptools-rust#438]
### Bug Description

I tried to use maturin through `poetry` but on MINGW + msys2 the compilation of maturin failed 😇 

### Minimal working example

- Example repository: https://github.com/y-yu/poetry-maturin-mingw-msys2
- Example GitHub Actions result: https://github.com/y-yu/poetry-maturin-mingw-msys2/actions/runs/9698478876/job/26765121620#step:6:1190
    ```
       error: Rust build failed; unable to locate executable 'maturin'
    ```
    - I think this error cause from `setuptools_rust` 🤔  
        - https://github.com/PyO3/setuptools-rust/blob/34c5f160a3a282ea568d0d285957edbdd927a9c7/setuptools_rust/build.py#L290-L292

### Your maturin version (`maturin --version`)

1.6.0

### Your Python version (`python -V`)

Python 3.11.9-1

### Your pip version (`pip -V`)

pip 24.0-1

### What bindings you're using

None

### Does `cargo build` work?

- [x] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [x] Yes

### Steps to Reproduce

1. Prepare msys2 + MINGW, `poetry` and Rust
2. `git clone https://github.com/y-yu/poetry-maturin-mingw-msys2.git`
3. `cd poetry-maturin-mingw-msys2`
4. `poetry install`

**Comment by messense** [comment]
I don't have a MINGW + mysys2 environment, so it would be really helpful if you can get the JSON output of `cargo build --message-format=json` for maturin.

**Comment by y-yu** [comment]
OK 🙆‍♀️ 
I forked maturin and tried to run `cargo build --manifest-path Cargo.toml --message-format=json-render-diagnostics --release -v --no-default-features --locked` for maturin on MINGW + msys2 👇 using GitHub Actions

```json
{
  "reason": "compiler-artifact",
  "package_id": "path+file:///D:/a/maturin/maturin#1.6.0",
  "manifest_path": "D:\\a\\maturin\\maturin\\Cargo.toml",
  "target": {
    "kind": [
      "bin"
    ],
    "crate_types": [
      "bin"
    ],
    "name": "maturin",
    "src_path": "D:\\a\\maturin\\maturin\\src/main.rs",
    "edition": "2021",
    "doc": true,
    "doctest": false,
    "test": true
  },
  "profile": {
    "opt_level": "3",
    "debuginfo": 0,
    "debug_assertions": false,
    "overflow_checks": false,
    "test": false
  },
  "features": [],
  "filenames": [
    "D:\\a\\maturin\\maturin\\target\\release\\maturin.exe"
  ],
  "executable": "D:\\a\\maturin\\maturin\\target\\release\\maturin.exe",
  "fresh": false
}
```

- https://github.com/y-yu/maturin/actions/runs/9682417847/job/26715379640#step:6:911

It looks good to me so I don't understand why maturin compilation fails  🤔 

PS. Actually I don't have a MINGW + msys2 environment too 🙄 (I need to distribute wheels for Windows)

**Comment by y-yu** [comment]
Eventually I found why the problem happened 👍 , and sorry the root problem is certainly `poetry`, or something no matter for `setuptools_rust` / `maturin` 🙇 🙇 

To investigate this issue, I wrote the Python code such above 👇 (this code print the environment on which it runs)

```python
import os
import platform

def main():
    print(os.name)
    print(platform.system())

if __name__ == "__main__":
    main()
```

And run this code by

1. Pure `python`, which is installed by MINGW + msys2
2. `poetry`, which is installed by `pip install --upgrade poetry --no-binary :all:` (this PR's way)

#### 1. Pure `python` result

```console
$ python python/hello_world/main.py
nt
Windows
```

- https://github.com/y-yu/poetry-maturin-mingw-msys2/actions/runs/9730114779/job/26852793651#step:6:7

#### 2. `poetry` installed by this PR's way

```console
$ poetry run python python/hello_world/main.py
posix
MINGW64_NT-10.0-20348
```

- https://github.com/y-yu/poetry-maturin-mingw-msys2/actions/runs/9729996080/job/26852536877#step:7:7

So `poetry` runs on `posix` mode but the `cargo build --message-format=json` result contains Windows `\` style path 👇 

```json
"filenames": [
    "D:\\a\\maturin\\maturin\\target\\release\\maturin.exe"
]
```

Finally `Path("D:\\a\\maturin\\maturin\\target\\release\\maturin.exe").with_suffix("").name` won't work fine 😇 

I don't see why `poetry` runs Python code on `posix` mode, anyway I close this issue.
