### ISSUE TITLE
`python -m pip install -e .` builds `release` instead of `debug`

### ISSUE THREAD

**Issue by lycantropos** [PyO3/setuptools-rust#459]
I've started to get issues in CI, after debugging I can say that this commit
https://github.com/PyO3/setuptools-rust/commit/925b3ba4186ccd53ee8d123c07e03e60558f13b5
introduces changes that breaks previous behavior:
after running
```bash
> python -m pip install -e .
```
previously `target/debug` build was created and after that commit it started creating `target/release` instead, is it expected?

**Comment by davidhewitt** [comment]
Very sorry about that. I've prepared #460, can you maybe check if that fixes the problem?

If you don't have a chance to check, no problem, I'll push later when I get a chance.

**Comment by lycantropos** [comment]
yes, it does, looks great

**Comment by davidhewitt** [comment]
Thanks for confirming!
