### ISSUE TITLE
Constant name for the generated library when no binding is used

### ISSUE THREAD

**Issue by bmatthieu3** [PyO3/setuptools-rust#47]
Hi,

I have a simple python program (the repo is located here https://github.com/bmatthieu3/rust-pypi) that loads a dynamic library generated from cargo and using the CFFI package.

I would like to generate wheels for different platforms and for that purpose I am using setuptools-rust. I declare a new RustExtension with binding=NoBinding. (See https://github.com/bmatthieu3/rust-pypi/blob/master/setup.py )

I have noticed that depending on the version of python I'm using, the name of the library generated (a .so on linux) changes when I'm doing the command:
`python setup.py build_rust`

Compiling using python2 works as it generates the lib with the expected name (``rust_pypi.so``). That file will be correctly found by my python script.
However when executing the previous command using python3.6 I get a ``rust_pypi.cpython-36m-x86_64-linux-gnu.so`` . In other words, for all the python3.6 wheels, my python package will not be able to found the dynamic library.

How can I set a constant library name and be sure that it will always remain for the wheels that will be generated (independently from the platform and the python version used) ?

Thank you for your answer,
Matthieu

**Comment by messense** [comment]
`rust_pypi.cpython-36m-x86_64-linux-gnu.so` is a correct Python native extension name, it was defined by [PEP 3149 -- ABI version tagged .so files](https://www.python.org/dev/peps/pep-3149/)
