### ISSUE TITLE
Problems trying to build a hello world app using setuptools-rust

### ISSUE THREAD

**Issue by brupelo** [PyO3/setuptools-rust#52]
I've created a hello world app [https://github.com/brupelo/pysublime_fuzzy](https://github.com/brupelo/pysublime_fuzzy) and when I try to generate some wheels out of it I'm facing some errors:

    [vagrant@localhost ~]$ git clone https://github.com/brupelo/pysublime_fuzzy
    Cloning into 'pysublime_fuzzy'...
    remote: Enumerating objects: 23, done.
    remote: Counting objects: 100% (23/23), done.
    remote: Compressing objects: 100% (16/16), done.
    remote: Total 23 (delta 6), reused 20 (delta 3), pack-reused 0
    Unpacking objects: 100% (23/23), done.
    [vagrant@localhost ~]$ cd pysublime_fuzzy/
    [vagrant@localhost pysublime_fuzzy]$ docker pull quay.io/pypa/manylinux1_x86_64
    Using default tag: latest
    latest: Pulling from pypa/manylinux1_x86_64
    7d0d9526f38a: Already exists
    54e27cdac081: Already exists
    45d8f3bab714: Already exists
    b2e1d01082bb: Already exists
    Digest: sha256:c47410598bc47614ef19b4320cf8203f1597bf847c9e504c2b0ba41af7c0f824
    Status: Image is up to date for quay.io/pypa/manylinux1_x86_64:latest
    [vagrant@localhost pysublime_fuzzy]$ docker run --rm -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /io/build-wheels.sh
    docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/io/build-wheels.sh\": permission denied": unknown.
    [vagrant@localhost pysublime_fuzzy]$

Any idea how to proceed here? I've been trying for hours trying to figure out how to build my rust stuff for linux with no success so far.

Thanks in advance.

**Comment by brupelo** [comment]
I've made some little progress but I'm still stuck at:

    [vagrant@localhost pysublime_fuzzy]$ docker run --rm -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 sh -c "/io/build-wheels.sh"
    sh: /io/build-wheels.sh: Permission denied
    [vagrant@localhost pysublime_fuzzy]$ chmod +x build-wheels.sh
    [vagrant@localhost pysublime_fuzzy]$ docker run --rm -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 sh -c "/io/build-wheels.sh"
    + curl https://sh.rustup.rs -sSf
    + sh -s -- --default-toolchain nightly -y
    info: downloading installer
    info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
    info: latest update on 2019-03-22, rust version 1.35.0-nightly (94fd04589 2019-03-21)
    info: downloading component 'rustc'
    info: downloading component 'rust-std'
    info: downloading component 'cargo'
    info: downloading component 'rust-docs'
    info: installing component 'rustc'
    info: installing component 'rust-std'
    info: installing component 'cargo'
    info: installing component 'rust-docs'
    info: default toolchain set to 'nightly'

      nightly installed - rustc 1.35.0-nightly (94fd04589 2019-03-21)


    Rust is installed now. Great!

    To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
    environment variable. Next time you log in this will be done automatically.

    To configure your current shell run source $HOME/.cargo/env
    + export PATH=/root/.cargo/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    + PATH=/root/.cargo/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    + cd /io
    + for PYBIN in '/opt/python/{cp36-cp36m}/bin'
    + export 'PYTHON_SYS_EXECUTABLE=/opt/python/{cp36-cp36m}/bin/python'
    + PYTHON_SYS_EXECUTABLE='/opt/python/{cp36-cp36m}/bin/python'
    + '/opt/python/{cp36-cp36m}/bin/pip' install -U setuptools wheel setuptools-rust
    /io/build-wheels.sh: line 12: /opt/python/{cp36-cp36m}/bin/pip: No such file or directory
    [vagrant@localhost pysublime_fuzzy]$

**Comment by althonos** [comment]
It looks like a syntax error: in your script, `{cp36-cp36m}` should read `{cp36,cp36m}`.

**Comment by brupelo** [comment]
@althonos Right now I'm trying to learn a little bit more about docker so I can test properly this stuff... :) , one thing I'm trying to figure out now is how to persist the rust installation so each time I rebuild my python binaries I won't need quite a lot while rust installs... almost there.

Thanks for your hint btw ;)

**Comment by brupelo** [comment]
As suggested in the landing page, [pyo3-pack](https://github.com/PyO3/pyo3-pack) should be used instead this project.
