### ISSUE TITLE
`setup.py develop` blocks later usage of optimized builds

### ISSUE THREAD

**Issue by clbarnes** [PyO3/setuptools-rust#55]
I'm not sure about the parallels between setuptools and setuptools-rust in this case (pretty hazy on a lot of the details tbh), but here's a problem we came across. It may just need documenting as it's a bit of a gotcha.

When you `setup.py install`, the egg gets built with a release/optimized binary and then copied to your site-packages. When you `setup.py develop`, the egg gets built with a debug binary, which is copied into your python source tree, and then that is symlinked ?somewhere?. The important thing is that even if you `setup.py install` *after* having `setup.py develop`ed, the old debug binary is found via the symlink to the source tree before the new optimized binary ins site-packages. We were wondering why our benchmarks were around 50x slower than expected (credit to @aschampion for figuring it out).

This possibly impacts the use of `usedevelop` in the tox config (#3) - while it might be nice to run unit tests against a debug build, if you're using something like pytest-benchmark you want pytest to be running against the optimized build.

**Comment by clbarnes** [comment]
Related:

> By default, develop will create a debug build, while install will create a release build.

Is it possible to customise this when calling e.g. `setup.py test`? Our use case is that we want pytest to run our benchmarks, but some combination of pytest's path mangling and setuptools-rust's build configuration makes it impossible to read the optimized version of our library from site-packages.

**Comment by althonos** [comment]
Hi @clbarnes ,

I don't have a good solution for this, given the compiled binary must be copied to the `build` directory in a location `setuptools` is expecting it, so there's no way to really check with which profile a binary was built.

However, you can force the compilation in debug or release mode using the `build_rust` subcommand: 
`python setup.py build_rust -r develop` will compile in release mode before using develop, or `python setup.py build_rust -r install` to make sure you always install the debug binary.

**Comment by clbarnes** [comment]
Great, that should do fine!
