### ISSUE TITLE
Incorrectly pack multiple versions of .so in one wheel

### ISSUE THREAD

**Issue by pjw91** [PyO3/setuptools-rust#60]
When using build-wheels.sh, in the for-loop of `PYBIN`:

1. When `PYBIN=py35`, `pip wheel` generates `build/lib/xxx.cpython-35m-x86_64-linux-gnu.so` and pack it into `py35.whl`

1. When `PYBIN=py36`, `pip wheel` generates `build/lib/xxx.cpython-36m-x86_64-linux-gnu.so` and pack BOTH `py35.so` and `py36.so` into `py36.whl`

and so on.

Thus, the resulting py38.whl contains all .so files, from py35.so to py38.so.

I don't how setuptools works, maybe the `build/lib` should be cleaned in advance?

**Comment by althonos** [comment]
Hi @pjw91 ,
after checking with another project using `setuptools` to build a C extension, I can confirm that `setuptools` and `wheel` always embed every possible `.so` in the generated wheel. I'll edit the script so that old `.so` are removed when compiling the wheels.

**Comment by pjw91** [comment]
I see the latest commit f10f4d7.

However, the filename of a generated so may be "<project>.<cpython-version>-<arch>.so", where the "project" might not be prefixed with "lib."

Another issue is that, in the "build-wheel.sh", the environment variables (LD_LIBRARY_PATH, LIBRARY_PATH) are stacked during the loop, which "might" causes problems.

**Comment by Askaholic** [comment]
Can this be added to the version of build-wheels.sh in the README too? I copy/pasted from the readme and just noticed this issue.
