### ISSUE TITLE
build working for linux, macos and windows with github actions

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/setuptools-rust#61]
I've just setup [rtoml](https://github.com/samuelcolvin/rtoml) to build and upload binaries for linux, macos and windows using github actions with setuptools-rust.

The build uses [cibuildwheel](https://github.com/joerick/cibuildwheel) rather than the manual `build-wheels.sh` approach. See [here](https://github.com/samuelcolvin/rtoml/blob/e834a1ef2a51d4777a5bd99b03b671f719d217a7/.github/workflows/ci.yml#L60-L134) for details.

This is not an issue or request for any changes (though perhaps it would be helpful to add a link to rtoml as an example?) so feel free to close this issue, I just thought it might be a helpful pointer for anyone else using PyO3 and/or setuptools-rust.

Thanks so much for PyO3 and setuptools-rust.

**Comment by althonos** [comment]
Thanks, I'll add a section with project examples to the README when I get some time.
