### ISSUE TITLE
Docker build images

### ISSUE THREAD

**Issue by cathalgarvey** [PyO3/setuptools-rust#7]
Hey folks,

I've just gone through building a docker image just to build binary wheels for a version of python I didn't have installed.

For the whole Rust:Python interact, it'd be cool to have a set of docker images with various Python/Rust versions and `setuptools-rust` preinstalled, to facilitate the ecosystem better.

Is anyone working on this already? I'm not a very good candidate for "dockerfile maintainer" as I have very limited experience so far, but I may still start a crappy repo if nobody else is doing yet yet.

**Comment by fafhrd91** [comment]
docker image would be useful, I could use it for async-tokio. but I am not very familiar with docker.

**Comment by cathalgarvey** [comment]
:) That makes two of us: I just did the following:

1. Pasted together a Python base image and the gust of [this](https://hub.docker.com/r/liuchong/rustup/~/dockerfile/)
1. Called it in the python project directory with `sudo docker run -v $(pwd):$(pwd) -w $(pwd) <image_hash> python3 setup.py bdist_wheel`

That allowed it to build-in-place the wheel I needed.
So, that's a cheap hack that "works for me", but making this useful would mean having an array of python:rust versions and tagging them properly, and then maintaining them in a repo somewhere, and hosting images on docker hub. *probably* not a ridiculous amount of work, though fraught with peril for the inexperienced (it me).

**Comment by mckaymatt** [comment]
I was working on a similar project where I build Rusty Python binary wheels using
1. TravisCI+Appveyor for multi-platform build
2. Docker and specifically the manylinux compatible containers   
3. [Cookiecutter](https://github.com/audreyr/cookiecutter) for the project template. 

The only part I am missing is a Rust setuptools module 

Let me see what I can do with your setuptools module + all that stuff I'm working on. 

more on  manylinux containers from https://github.com/pypa/manylinux  and the pep https://www.python.org/dev/peps/pep-0513

**Comment by cathalgarvey** [comment]
Oo, looks interesting; thanks!

On 16 May 2017 19:48:39 GMT+01:00, mckaymatt <notifications@github.com> wrote:
>I was working on a similar project where I build Rusty Python binary
>wheels using
>1. TravisCI+Appveyor for multi-platform build
>2. Docker and specifically the manylinux compatible containers   
>3. [Cookiecutter](https://github.com/audreyr/cookiecutter) for the
>project template. 
>
>The only part I am missing is a Rust setuptools module 
>
>Let me see what I can do with your setuptools module + all that stuff
>I'm working on. 
>
>more on  manylinux containers from https://github.com/pypa/manylinux 
>and the pep https://www.python.org/dev/peps/pep-0513
>
>
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PyO3/setuptools-rust/issues/7#issuecomment-301878460

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by messense** [comment]
I added a script to build `manylinux1` wheels for the example project:

https://github.com/PyO3/setuptools-rust/blob/master/example/build-wheels.sh

**Comment by fafhrd91** [comment]
Awesome!

**Comment by fafhrd91** [comment]
@messense could you add same text to main readme

**Comment by messense** [comment]
Added.

**Comment by sbellem** [comment]
The script to build `manylinux1` wheels is now at https://github.com/PyO3/setuptools-rust/blob/master/build-wheels.sh.
