### ISSUE TITLE
Please include version in setup.cfg

### ISSUE THREAD

**Issue by tiran** [PyO3/setuptools-rust#91]
I'm currently in the process to package setuptools-rust for Fedora Linux. There is a small, easy to fix problem in packaging of setuptools-rust. ``setup.cfg`` does not include version number of the package. The RPM packaging build chain re-creates the egg-info directory based on information from ``setup.py`` and ``setup.cfg``. Without a version entry in setup.cfg, setuptools assumes version ``0.0.0``.

```
$ rpmbuild -bb python-setuptools-rust.spec
...
RPM build errors:
    File not found: /BUILDROOT/python-setuptools-rust-0.11.5-1.fc32.x86_64/usr/lib/python3.8/site-packages/setuptools_rust-0.11.5-py3.8.egg-info
$ ls /BUILDROOT/python-setuptools-rust-0.11.5-1.fc32.x86_64/usr/lib/python3.8/site-packages/
setuptools_rust  setuptools_rust-0.0.0-py3.8.egg-info
```

* https://packaging.python.org/guides/distributing-packages-using-setuptools/#version
* https://packaging.python.org/guides/distributing-packages-using-setuptools/#choosing-a-versioning-scheme

**Comment by tiran** [comment]
The change may not be required after all. I have tracked down the issue to setuptools. The build failure might be caused by a bug in setuptools < 42 and an unsufficient version requirement in setuptools_scm. My work machine is on Fedora 32 with setuptools 41.6.

I have filed https://github.com/pypa/setuptools_scm/pull/504 with setuptools_scm and requested a version bump to setuptools >= 42.

**Comment by althonos** [comment]
No, I still think it's a good idea to have the version in `setup.cfg`, plus maybe somewhere in `__init__.py`. Starting with `setuptools >= 46.1` we can write the version in `__init__.py` and use `attr: setuptools_rust.__version__` in `setup.cfg`.

**Comment by tiran** [comment]
That sounds like a great idea!

Ronny has merged my PR to bump minimum setuptools versions to 42. He will release a new version of setuptools_scm next week.

I can also confirm that my issue was caused by old setuptools and setuptools_scm. The version field is autofilled with setuptools_scm 4.1.2 and setuptools 49 of Fedora 33.

**Comment by tiran** [comment]
I have updated my PR #93 to use ``version = attr: setuptools_rust.__version__``.
