### ISSUE TITLE
GitHub and Conda package sources for v0.11.6 don't match

### ISSUE THREAD

**Issue by Quogu** [PyO3/setuptools-rust#97]
I'm keen to use the change in https://github.com/PyO3/setuptools-rust/commit/060d8b4b4ad5f3a5173466a2f47ea74eda70f6e7 as I'd like to build using GNU instead of MSVC on Windows. That change was committed on 2020-11-14, and https://github.com/PyO3/setuptools-rust/tree/v0.11.6 was produced on 2020-12-13, and I can see the commit I care about in that tag's history. However, https://anaconda.org/conda-forge/setuptools-rust/0.11.6/download/noarch/setuptools-rust-0.11.6-pyhd8ed1ab_0.tar.bz2 doesn't contain this change.

This seems to indicate a problem of the release process here, if the GitHub and Conda sources don't match. Is this something that can be looked into, please?

**Comment by davidhewitt** [comment]
Thanks for the report - I think it's a downstream issue at https://github.com/conda-forge/setuptools-rust-feedstock/issues/10

**Comment by davidhewitt** [comment]
Fixed downstream. Thanks for the report.
