### ISSUE TITLE
ubuntu cannot find rust compiler

### ISSUE THREAD

**Issue by herbyboi** [PyO3/setuptools-rust#98]
Currently I face the issue someone had here https://github.com/PyO3/setuptools-rust/issues/54. Sadly i cannot preform the command without sudo, as I cant really change the requirements for every file it needs to access. Entering root mode is impossible on ubuntu, and running the command from bash file with sudo doesnt work either. 

OS: lubuntu 18.04
CMD: python3 setup.py install
without sudo: Errno 13 permission denied
with sudo: Cannot find rust compiler

How do I run it?

**Comment by davidhewitt** [comment]
As this is basically down to whatever you've put on your filesystem, without knowing what files you've not got access to, I'm unlikely to be much help. Have you tried using `rustup` to install a rust compiler as root?

**Comment by davidhewitt** [comment]
Closing as stale.
